services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    env_file:
      - .env
    volumes:
      - .:/var/www/html
      - ${CI_SERVICE_ACCOUNT_JSON_KEY_PATH-./tests/Support/gcloud-key-valid.json}:/var/www/html/tests/Support/gcloud-key-valid.json
  mysql:
    image: 'mysql:${MYSQL_VERSION:-8.0}'
    ports:
      - '${MYSQL_PORT:-3307}:3306'
    environment:
      MYSQL_USER: 'cloudtasks'
      MYSQL_PASSWORD: 'cloudtasks'
      MYSQL_DATABASE: 'cloudtasks'
      MYSQL_ROOT_PASSWORD: 'root'
  pgsql:
    image: 'postgres:${PGSQL_VERSION:-14}'
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: 'cloudtasks'
      POSTGRES_PASSWORD: 'cloudtasks'
      POSTGRES_DB: 'cloudtasks'
